home:
  link1: "https://www.railstutorial.org"
  link2: "https://rubyonrails.org"
help:
  link1: "https://www.railstutorial.org/help"
  link2: "https://www.railstutorial.org/book"
about:
  link1: "https://www.railstutorial.org"
  link2: "https://www.learnenough.com"
  link3: "https://www.railstutorial.org/book"
  link4: "https://screencasts.railstutorial.org"
contact:
  link1: "https://www.railstutorial.org/contact"
footer:
  link1: "https://www.railstutorial.org"
  link2: "https://www.michaelhartl.com"
  link3: "https://news.railstutorial.org"
